name: Angular GitHub CI
on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install Dependencies
        run: 
          npm ci
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Build
        run: 
          CI=true && npm run build


      - name: Test
        run: 
          CI=true && npm test 
      
      